### PR TITLE
Implement evmTrace

### LINKED ISSUE #114: Add evm tracing debug method
Similar to the `evmStackTrace` method in `ewasm-kernel`: https://github.com/ewasm/ewasm-kernel/blob/master/debugInterface.js#L30-L40

It should target to have all the content needed for the tracing format as described here: https://github.com/ethereum/tests/issues/249

I propose the following: `evmTrace(pc: i32, opcode: i32, cost: i32, sp: i32)`

It will then output the following JSON: `{'pc': $pc, 'op': $opcode, 'gas': $gasLeft, 'gasCost': $cost, 'stack': $stack, 'depth': $depth}` where `$gasLeft` and `$depth` are the current values from the environment and `$stack` is an array of reading 32 bytes from `memory_start + $pc` and decreasing `$pc` by 32 until it is less than 0.

### PR DESCRIPTION
**Pull request by axic**
Fixes #114.

### CODE REVIEW

**Comment by axic** [comment]
@jakelang this was my skeleton, do you want to work on this?

**Comment by jakelang** [comment]
@axic done. I did not see this until I had already implemented the method on a branch of the same name, hence I had to clean up a bit.

**Comment by axic** [comment]
@jwasinger @cdetrio @jakelang  is the stack dump of the correct byteorder?

**Comment by cdetrio** [comment]
When I last tried, this was how it looked:

```
$ test/testeth -t GeneralStateTests/stExample -- --testpath /home/ubuntu/cpp-ewasm/cpp-ethereum/test/jsontests --singlenet "Byzantium" --singletest "add11" --vm hera
Running 1 test case...
Test Case "stExample": 
100%
Executing...
useGas 12
evmTrace
sp: 0
{'pc': 1, 'op': 96, 'gas': 0x5c86c, 'gasCost': 0x3, 'stack': ['0x'], 'depth': 0}
evmTrace
sp: 32
{'pc': 3, 'op': 96, 'gas': 0x5c86c, 'gasCost': 0x6, 'stack': ['0x10000000000000000000000000000000', '0x'0x'], 'depth': 0}
evmTrace
sp: 64
{'pc': 4, 'op': 1, 'gas': 0x5c86c, 'gasCost': 0x9, 'stack': ['0x10000000000000000000000000000000', '0x'0x20000000000000000000000000000000', '0x'0x'], 'depth': 0}
evmTrace
sp: 32
{'pc': 6, 'op': 96, 'gas': 0x5c86c, 'gasCost': 0xc, 'stack': ['0x20000000000000000000000000000000', '0x'0x'], 'depth': 0}
storageStore 40 20
evmTrace
sp: 64
{'pc': 7, 'op': 85, 'gas': 0x5b4e4, 'gasCost': 0xc, 'stack': ['0x00000000000000000000000000000000', '0x'0x00000000000000000000000000000002', '0x'0x'], 'depth': 0}
/home/ubuntu/cpp-ewasm/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(722): error: in "GeneralStateTests/stExample": add11 on Byzantium: Expected another postState hash! expected: 0x17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479 actual: 0x0db721d3b88c94539035f3e32488dea6f803ae2f50f6c098c5529be491b6818c in Byzantium data: 0 gas: 0 val: 0

*** 1 failure is detected (7 failures are expected) in the test module "Master Test Suite"
```

This is what it should look like:
```
$ test/testeth -t GeneralStateTests/stExample -- --testpath /home/ubuntu/cpp-ewasm/cpp-ethereum/test/jsontests --singlenet "Byzantium" --singletest "add11" --jsontrace '{"disableMemory":true}'
Running 1 test case...
Test Case "stExample": 
100%
[
{"depth":"0","gas":"379000","gasCost":"3","op":"PUSH1","pc":"0","stack":[],"storage":{}},
{"depth":"0","gas":"378997","gasCost":"3","op":"PUSH1","pc":"2","stack":["0x01"]},
{"depth":"0","gas":"378994","gasCost":"3","op":"ADD","pc":"4","stack":["0x01","0x01"]},
{"depth":"0","gas":"378991","gasCost":"3","op":"PUSH1","pc":"5","stack":["0x02"]},
{"depth":"0","gas":"378988","gasCost":"0","op":"SSTORE","pc":"7","stack":["0x02","0x00"]},
{"depth":"0","gas":"358988","gasCost":"0","op":"STOP","pc":"8","stack":[],"storage":{"0x00":"0x02"}}
]
{"stateRoot": "17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479"}
*** No errors detected
```

**Comment by axic** [comment]
- Should the values always be strings?
- Should the hex numbers be decimals encoded as strings?
- Does `op` needs to be a text and not an actual opcode?
- Does the stack must be truncated to shortest hex representation?

These indeed look like bugs:
`['0x']`
`'0x'0x']`

**Comment by axic** [comment]
@chfast do you want to take this up? You can use `evm2wasm` with the trace flag to compile an EVM code to a wasm bytecode invoking the trace method. Just make sure the trace output will be closer to what cpp-ethereum outputs.

**Comment by chfast** [comment]
It looks not like this:

```
{"depth":0,"gas":9223372036854775798,"gasCost":3,"op":96,"pc":1,"stack":[]}
{"depth":0,"gas":9223372036854775798,"gasCost":6,"op":96,"pc":3,"stack":["0x00000000000000000000000000000000000000000000000000000000000000ff"]}
{"depth":0,"gas":9223372036854775798,"gasCost":9,"op":99,"pc":8,"stack":["0x000000000000000000000000000000000000000000000000000000000fffffff","0x00000000000000000000000000000000000000000000000000000000000000ff"]}
```

for code `60ff60ff630fffffffa1`.

There are issues on evm2wasm side, and not all values are correct.

If that's ok, I will squash commits and merge it.

**Pull request merged**
