### PR TITLE
[WIP] Fix ewasm testing

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
This is the last run of the old `ewasm-tests` task: https://circleci.com/gh/ewasm/hera/4141

The output is 
```
Running tests using path: "./tests"
Running 1 test case...
Test Case "stEWASMTests": 
Executing...
importGlobals
useGas 1000000
getGasLeft
storageStore 0 20
Executing...
importGlobals
externalCodeCopy 0 c8 0 a
storageStore 64 c8
Executing...
importGlobals
callDataCopy 101818 0 80
storageStore 1019f0 1019b0
Executing...
importGlobals
getBlockTimestamp
storageStore 64 0
Executing...
importGlobals
getBlockNumber
storageStore 0 20
Executing...
importGlobals
finish 0 0
Zero-length memory load from offset 0x0
Executing...
importGlobals
callDataSize
storageStore 0 20
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
create ffffffff 0 0 0
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
finish 0 ffffffff
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
$call 186a0 0 20 ffffffff 1
Out of bounds (source) memory copy.
Executing...
importGlobals
finish 0 14
Executing...
importGlobals
getTxGasPrice 0
storageStore 64 0
Executing...
importGlobals
$callDelegate 30d40 0 0 14 2
Executing...
importGlobals
getAddress 20
storageStore 0 20
finish 40 2
Executing...
importGlobals
getBalance 0 64
storageStore c8 64
Executing...
importGlobals
getTxOrigin 0
storageStore 64 0
Executing...
importGlobals
$call 30d40 0 40 60 0
Executing...
importGlobals
callDataSize
storageStore 80 e0
callDataCopy c0 0 0
Zero-length memory store to offset 0xc0
storageStore a0 c0
storageStore 20 80
Executing...
importGlobals
storageStore ffff0 fffd0
Executing...
importGlobals
finish 0 2
Executing...
importGlobals
storageLoad 0 1f4
storageStore 190 1f4
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
storageStore c0 100
revert 0 2
getReturnDataSize
storageStore 80 e0
getReturnDataSize
returnDataCopy 40 0 2
storageStore a0 40
storageStore c0 60
Executing...
importGlobals
getBlockHash 0 60
storageStore 0 60
storageStore 20 40
24%...
Executing...
importGlobals
$callStatic 30d40 0 0 14 2
Executing...
importGlobals
getAddress 20
storageStore 62 20
Static mode violation in storageStore.
Executing...
importGlobals
getCaller 20
selfDestruct 20
Executing...
importGlobals
$callStatic 30d40 0 0 34 0
Executing...
importGlobals
Static mode violation in call.
Executing...
importGlobals
getBlockNumber
storageStore 0 20
Executing...
importGlobals
create 40 100 122 96
Executing...
importGlobals
getCallValue 200
storageStore 220 200
finish 180 72
storageStore 0 0
storageStore 20 60
$call 30d40 60 80 80 80
Executing...
importGlobals
storageStore 280 2a0
storageStore a0 0
Executing...
importGlobals
unreachable
Executing...
importGlobals
$callDelegate 186a0 0 0 20 ffffffff
Out of bounds (source) memory copy.
Executing...
importGlobals
getBlockDifficulty 20
storageStore 0 20
Executing...
importGlobals
$callStatic 186a0 0 0 20 ffffffff
Out of bounds (source) memory copy.
Executing...
importGlobals
useGas 5221880
getGasLeft
Out of gas.
Executing...
importGlobals
callDataCopy fffd0 0 2
storageStore ffff0 fffd0
Executing...
importGlobals
$call 30d40 0 40 60 0
Executing...
importGlobals
callDataSize
storageStore 80 e0
callDataCopy c0 0 0
Zero-length memory store to offset 0xc0
storageStore a0 c0
storageStore 20 80
Executing...
importGlobals
create 40 100 89 96
Executing...
importGlobals
getCallValue 200
storageStore 220 200
storageStore 0 0
storageStore 20 60
Executing...
importGlobals
$call 30d40 0 40 60 0
Executing...
importGlobals
callDataSize
storageStore 80 e0
callDataCopy c0 0 0
Zero-length memory store to offset 0xc0
storageStore a0 c0
storageStore 20 80
Executing...
importGlobals
$callCode 186a0 0 20 20 1
Executing...
importGlobals
storageStore 0 20
storageStore 80 60
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
create 0 ffffffff 1 0
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
create 0 0 ffffffff 0
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
log 0 0 5
Too many topics specified
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
callDataCopy 20 0 2
storageStore 0 20
Executing...
importGlobals
Out of bounds (source) memory copy.
Executing...
importGlobals
getCaller 20
selfDestruct 20
Executing...
importGlobals
$call 186a0 0 20 20 ffffffff
Out of bounds (source) memory copy.
49%...
Executing...
importGlobals
getExternalCodeSize 0
externalCodeCopy 0 40 31 a
Out of bounds (source) memory copy
Executing...
importGlobals
getBlockCoinbase 20
storageStore 0 20
Executing...
importGlobals
getCallValue 20
storageStore 0 20
Executing...
importGlobals
finish 0 6000
Executing...
importGlobals
callDataSize
storageStore ffff0 fffec
Executing...
importGlobals
$call 186a0 200 0 0 0
Executing...
importGlobals
getCodeSize
codeCopy 0 93 a
Out of bounds (source) memory copy.
storageStore 20 60
storageStore 40 80
Executing...
importGlobals
finish 0 8
Executing...
importGlobals
Out of bounds (source) memory copy.
Executing...
importGlobals
useGas 1000
Executing...
importGlobals
getCodeSize
codeCopy 40 c4 a
Out of bounds (source) memory copy.
Executing...
importGlobals
getBlockHash 1 60
storageStore 0 60
storageStore 20 40
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
log 0 0 1
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
callDataCopy 20 0 20
storageStore 0 20
Executing...
importGlobals
getAddress fffd0
storageStore ffff0 fffd0
Executing...
Error in parsing WASM binary: 'bad signature form -15' at 18446744073709551615:18446744073709551615
Executing...
importGlobals
getCaller 20
storageStore 0 20
Executing...
importGlobals
getBlockHash 0 60
storageStore 0 60
storageStore 20 40
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
log 0 ffffffff 0
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
getCodeSize
storageStore 0 20
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
create 0 0 0 4294967295
Out of bounds (destination) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
finish 0 6001
74%...
Executing...
importGlobals
codeCopy 0 0 a
storageStore 64 0
Executing...
importGlobals
$call 186a0 200 0 0 0
Executing...
importGlobals
finish 800 4
getReturnDataSize
returnDataCopy 40 0 5
Out of bounds (source) memory copy.
Executing...
importGlobals
create 40 100 66 96
Executing...
importGlobals
finish 200 2
storageStore 0 0
storageStore 20 60
Executing...
importGlobals
$callDelegate 4e21 0 0 14 2
Executing...
importGlobals
getAddress 20
storageStore 0 20
Out of gas.
storageStore 56 36
Executing...
importGlobals
$call 186a0 200 0 0 0
Executing...
importGlobals
finish 800 4
getReturnDataSize
returnDataCopy 40 2 4
Out of bounds (source) memory copy.
Executing...
importGlobals
$call 30d40 0 40 60 0
storageStore 20 80
Executing...
importGlobals
getAddress 0
getBalance 0 64
storageStore c8 64
Executing...
importGlobals
$callCode 186a0 0 20 20 ffffffff
Out of bounds (source) memory copy.
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
log 0 0 ffffffff
Too many topics specified
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
getBlockGasLimit
storageStore 64 0
Executing...
importGlobals
$call 186a0 0 60 80 0
Executing...
importGlobals
finish 200 4
storageStore 20 c0
getReturnDataSize
returnDataCopy a0 0 4
storageStore 40 a0
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
revert 0 ffffffff
Out of bounds (source) memory copy.
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
finish 0 100
Executing...
importGlobals
getCodeSize
codeCopy 40 cc a
Out of bounds (source) memory copy.
Executing...
importGlobals
getExternalCodeSize 40
storageStore 0 20
Executing...
importGlobals
create 0 10 0 0
Executing...
importGlobals
$call 186a0 0 20 20 1
Executing...
importGlobals
log 0 0 4
Zero-length memory load from offset 0x0
getReturnDataSize
storageStore 80 e0
storageStore a0 60
Executing...
importGlobals
getExternalCodeSize 0
externalCodeCopy 0 40 2c a
Out of bounds (source) memory copy
Executing...
importGlobals
$call 30d40 0 40 60 2
Executing...
importGlobals
callDataSize
storageStore 80 e0
callDataCopy c0 0 2
storageStore a0 c0
storageStore 20 80
Executing...
importGlobals
create 40 100 66 96
Executing...
importGlobals
finish 200 2
storageStore 0 0
storageStore 20 60
Executing...
importGlobals
getAddress 20
storageStore 0 20
Executing...
importGlobals
$call 186a0 200 0 0 0
Executing...
importGlobals
finish 800 4
getReturnDataSize
returnDataCopy 40 4 4
Out of bounds (source) memory copy.
98%...
Executing...
importGlobals
$call 30d40 0 40 60 2
Executing...
importGlobals
callDataSize
storageStore 80 e0
callDataCopy c0 0 2
storageStore a0 c0
storageStore 20 80
100%
Executing...
importGlobals
getAddress 0
getBalance 0 20
getGasLeft
storageStore 40 60

*** No errors detected
```

**Comment by chfast** [comment]
1. Run testeth with verbosity 2+.
2. Print the error code at the end of the script.

**Comment by chfast** [comment]
I believe I fixed it in Aleth 1.4.0rc4 #357

**Comment by axic** [comment]
Yes it seems it did.

**Pull request closed without merging**
