### PR TITLE
[WIP] Support WAVM in Hera

### PR DESCRIPTION
**Pull request by jakelang**
merges into vm-abstr

Part of #158.

### CODE REVIEW

**Comment by axic** [comment]
Extracted this basic logic from https://github.com/AndrewScheidecker/WAVM/blob/master/Source/Programs/wavm.cpp:
```
struct TestResolver : Runtime::Resolver
{
    bool resolve(
      const std::string& moduleName,
      const std::string& exportName,
      IR::ObjectType type,
      Runtime::Object*& outObject) override
    {
      return false;
    }
};

void wavm_test() {
  IR::Module module;
  if (!IR::loadModule("test.wasm", module)) abort();

  Runtime::Compartment* compartment = Runtime::createCompartment();
  Runtime::Context* context = Runtime::createContext(compartment);

  TestResolver resolver;
  Runtime::LinkResult linkResult = Runtime::linkModule(module, resolver);
  if (!linkResult.success) abort();

  Runtime::ModuleInstance* moduleInstance = IR::instantiateModule(
        compartment,
        module,
        std::move(linkResult.resolvedImports),
        "test.wasm");

  if (!moduleInstance) abort();
  
  Runtime::FunctionInstance* startFunction = moduleInstance->startFunction;
}
```

**Comment by jakelang** [comment]
@axic yeah that is what i was working off as well.

**Comment by axic** [comment]
Can this be rebased against master? (Need to create `wavm.cpp`.)

**Comment by axic** [comment]
@jakelang do you want to keep this PR alive or should we close it?

**Comment by jakelang** [comment]
@axic I am pretty sure we should close this, as @poemm is working on it and probably has made further progress than this.

**Pull request closed without merging**
