### PR TITLE
Upgrade EVMC to version 7.0.0

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
@chfast okay to merge this if we ignore codecov?

**Comment by chfast** [comment]
> @chfast okay to merge this if we ignore codecov?

There are some issues with finding `evmc-vmtester`.

**Comment by axic** [comment]
Btw in the `ci` branch I started updating to using newer cpp-build-env, but building WAVM fails with LLVM 6 not being installed. Perhaps those new build images are needed to get this one working?

**Comment by axic** [comment]
Verified with a local build of `evmc-vmtester`.

**Pull request merged**
