### PR TITLE
[WIP] Update to EVMC ABIv6

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
@chfast for some reason `testeth` doesn't properly abort if the ABI is incompatible version..

```
testeth 1.4.0rc5
[2018-09-03 23:45:44.536526] [0x00007fb90f9ca800] [info]    Loading EVMC module: /home/builder/build/src/libhera.so
Running tests using path: "tests"
Running 1 test case...
Test Case "stEWASMTests": 
/home/builder/project/test/tools/libtesteth/ImportTest.cpp(753): error: in "GeneralStateTests/stEWASMTests": callStaticVeryLong on Byzantium: Expected another postState hash! expected: 0xa796755cd4134b7de3f118fa3b83bbff808f13d58f4acd3140d9ab8041799945 actual: 0x7e50595b5632407b00ee0338d68abea777e4be6ef3908f8ddf7627e280c619c0 in Byzantium data: 0 gas: 0 val: 0
unknown location(0): fatal error: in "GeneralStateTests/stEWASMTests": memory access violation at address: 0x00000000: no mapping at fault address
/home/builder/project/test/tools/libtesteth/TestHelper.cpp(595): last checkpoint
```

**Comment by axic** [comment]
So apparently rc6 is even worse:
```
testeth 1.4.0rc6
Received 'segmentation fault' signal
```

**Comment by chfast** [comment]
Replaced by #443

**Comment by axic** [comment]
I've way more much liked the iterative approach then the new PR which collapses every single change into one. Really hard to follow.

**Pull request closed without merging**
