### PR TITLE
Upgrade EVMC to version 6.0.0

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
Rebased.

**Comment by hugo-dc** [comment]
@axic the fillers are removed here in this same PR: https://github.com/ewasm/hera/blob/8e5a263e1c18d83e1b89a0a2bc17918cc86a6a4d/circle.yml#L129-L130

**Comment by chfast** [comment]
These were just warnings, not failures. They are fixed now.
Anyway, testeth still complains about fillers mismatch.

**Comment by axic** [comment]
Depends on https://github.com/ewasm/tests/pull/103

**Pull request merged**
