### PR TITLE
Use Cable

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
What is the benefit of cable here?

**Comment by chfast** [comment]
I thought we will need another CMake toolchain file for shared library, but it's not needed. So not big benefits, just the same compiler settings as in other C++ projects, and default build type being RelWithDebInfo.

**Comment by esteve** [comment]
I'm not familiar with Cable, so I don't really have an informed opinion, but it seems like a look idea to match the same compiler settings as the rest of the C++ project.

**Comment by axic** [comment]
@chfast merged in the `toHex` fix separately, please rebase.

**Comment by axic** [comment]
Rebased.

@chfast is this PR still needed though?

**Comment by axic** [comment]
@chfast ping

**Pull request closed without merging**
