### PR TITLE
Update EVMC to a4f7029 (ABI 3)

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
This has a failure (which is easy to fix):
```
/home/builder/project/src/hera.cpp: In function 'std::vector<unsigned char> {anonymous}::callSystemContract(evmc_context*, const evmc_address&, int64_t&, const std::vector<unsigned char>&)':
/home/builder/project/src/hera.cpp:101:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^
/home/builder/project/src/hera.cpp:101:3: sorry, unimplemented: non-trivial designated initializers not supported
/home/builder/project/src/hera.cpp:101:3: sorry, unimplemented: non-trivial designated initializers not supported
/home/builder/project/src/hera.cpp:101:3: sorry, unimplemented: non-trivial designated initializers not supported
/home/builder/project/src/hera.cpp:101:3: error: missing initializer for member 'evmc_message::flags' [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
```

But for some reason I do not get it on macos.

**Comment by axic** [comment]
Also I guess this PR needs to be pushed back until a rebuilt cpp-ethereum is pushed.

**Comment by axic** [comment]
@chfast this depends on a new aleth build with ABI3. It is currently using https://github.com/ethereum/cpp-ethereum/releases/download/v1.4.0.dev0/cpp-ethereum-1.4.0.dev0-linux.tar.gz

Do you think there will be one soon for ABI3?

**Comment by chfast** [comment]
After https://github.com/ethereum/cpp-ethereum/pull/5139 is merged I will make a new release.

**Comment by axic** [comment]
@chfast updated to use the release version (1.4.0rc0) on both static and shared tests.

**Pull request merged**
