### PR TITLE
Enable evm2wasm's evm trace output via CMake

### PR DESCRIPTION
**Pull request by jwasinger**
It occurs to me that we should be doing this at runtime.. Leaving this here anyways.

### CODE REVIEW

**Comment by jwasinger** [comment]
Apologize for the terrible branch name XD

**Comment by jwasinger** [comment]
ping @axic @chfast what do you think?

**Comment by chfast** [comment]
There is no way to handle this with command line option? Where do you plan to use it?

**Comment by jwasinger** [comment]
probably better as a CLI option,

**Pull request closed without merging**
