### PR TITLE
Ensure that balance/value is checked for as 128 bits and not 64 bits

### LINKED ISSUE #190: Value exceeds 64 bits
I wrote a [new test case](https://github.com/ewasm/tests/blob/test-low-balance/src/GeneralStateTestsFiller/stEWASMTests/callNotEnoughBalanceFiller.yml) in order to validate that we get an OOG exception when there is a call sending a value and the value is higher than the current sender Balance. Instead the result is the following:

```
100%
Executing...
importGlobals
DEBUG printMemHex(0x14:0x20): 20 a1 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
InternalError: Value exceeds 64 bits.
Executing...
importGlobals
DEBUG printMemHex(0x14:0x20): 20 a1 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
InternalError: Value exceeds 64 bits.
```

https://github.com/ewasm/hera/blob/1a219f0b5ebeaebbbb13639793d476f3fee6bf50/src/eei.cpp#L875

Here it is comparint the balance and value, both are u128 and it is being validated by a function that validates 64 bit numbers.

### PR DESCRIPTION
**Pull request by axic**
Part of #190.

### CODE REVIEW

**Comment by axic** [comment]
@hugo-dc here's a fix if you want to try

**Comment by hugo-dc** [comment]
Still getting an error:

InternalError: Value exceeds 128 bits.

It finds a non-zero byte in position 13 here: https://github.com/ewasm/hera/blob/3375c7eef8eef6ce42094c20ae12acf07710709a/src/eei.cpp#L902

**Comment by axic** [comment]
As mentioned in the issue there is still an endianess problem.

**Comment by hugo-dc** [comment]
LoadMemory loads 16 bytes of data into the first 16 bytes of `value`. When I send this value: `\20\a1\07\00\00\00\00\00\00\00\00\00\00\00\00\00`, I get the error I mentioned above (found a non-zero byte at position 13), if I send this value: `\00\00\00\00\00\00\00\00\00\00\00\00\00\07\a1\20` I get the same error, now indicating that the non-zero byte is in position 0.

```
i: 0
InternalError: Value exceeds 128 bits.
```

If I try to call sending 32 bytes it doesn't work either, because LoadMemory only reads 16 bytes (it would read only zeroes).

**Comment by axic** [comment]
I'm merging this because it fixes one problem, 64 -> 128 bits. Lets fix endianess separately.

**Pull request merged**
