### PR TITLE
Split wavm code for the ability of running GC

### PR DESCRIPTION
**Pull request by axic**
Idea from https://github.com/ewasm/hera/pull/394#issuecomment-421353465

### CODE REVIEW

**Comment by axic** [comment]
There are two leaks in wavm:
```
=================================================================
==2040==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7ff8ea975c68 in operator new(unsigned long) (/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so+0x11ac68)
    #1 0x7ff8e4e1b886 in LLVMJIT::getInvokeThunk(IR::FunctionType, Runtime::CallingConvention) (/home/builder/build/src/libhera.so+0x5e5886)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7ff8ea975c68 in operator new(unsigned long) (/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so+0x11ac68)
    #1 0x7ff8e4e20432 in JITThunkUnit::notifySymbolLoaded(char const*, unsigned long, unsigned long, std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >&&) (/home/builder/build/src/libhera.so+0x5ea432)

SUMMARY: AddressSanitizer: 280 byte(s) leaked in 2 allocation(s).
```

**Comment by axic** [comment]
In general I would prefer much more using `unique_ptr` and not `Runtime::GCPointer`. It seems hideous.

**Comment by chfast** [comment]
Better report as in https://github.com/ewasm/hera/pull/420.

```

Direct leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7fd32f521c68 in operator new(unsigned long) (/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so+0x11ac68)
    #1 0x7fd329a55990 in LLVMJIT::getInvokeThunk(IR::FunctionType, Runtime::CallingConvention) /home/builder/build/deps/src/wavm/Lib/Runtime/LLVMJIT.cpp:941:17


Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fd32f521c68 in operator new(unsigned long) (/usr/lib/clang/6.0/lib/linux/libclang_rt.asan-x86_64.so+0x11ac68)
    #1 0x7fd329a59f72 in JITThunkUnit::notifySymbolLoaded(char const*, unsigned long, unsigned long, std::map<unsigned int, unsigned int, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >&&) /home/builder/build/deps/src/wavm/Lib/Runtime/LLVMJIT.cpp:413:12
```

**Comment by chfast** [comment]
Both are WAVM bugs and must be fixed in WAVM:
https://github.com/WAVM/WAVM/blob/2c77c8a2e49bd291833d79fe6c68801b44ae634c/Lib/Runtime/LLVMJIT.cpp#L941
https://github.com/WAVM/WAVM/blob/2c77c8a2e49bd291833d79fe6c68801b44ae634c/Lib/Runtime/LLVMJIT.cpp#L413

**Comment by chfast** [comment]
Oh, this code has moved to some other place but I believe the problem persists. We should enable the same checks on #418.

**Pull request merged**
