### PR TITLE
don't use mktemp for hera evm2wasm.js

### PR DESCRIPTION
**Pull request by jwasinger**
Broken on debian-based environments.

### CODE REVIEW

**Comment by axic** [comment]
@jwasinger why is this need?

**Comment by jwasinger** [comment]
Try evm2wasm.js on a debian-environment.  the cpp-build-env image is debian (or maybe alpine?)

**Comment by axic** [comment]
You need to put in some kind of log showing what and how fails.

**Comment by jwasinger** [comment]
```
#include <stdio.h>
#include <string>
#include <string.h>
#include <iostream>
#include <stdlib.h>

using namespace std;

string mktemp_string(string pattern) {
  const unsigned long len = pattern.size();
  char tmp[len];
  strncpy(tmp, pattern.data(), len);
  if (!mktemp(tmp))
     return string();
  return string(tmp, len);
}

int main(int argc, char **argv) {
  string s = mktemp_string("/tmp/hera.evm2wasm.evm.XXXXXX");
  string s2 = mktemp_string("/tmp/hera.evm2wasm.evm.XXXXXX");
  cout << s << endl << s2;
}
```

This doesn't work in affected environments.

**Comment by axic** [comment]
This was fixed in #176.

**Pull request closed without merging**
