### PR TITLE
Add more entries to .gitignore

### PR DESCRIPTION
**Pull request by jakelang**
Also ignore swap files since this was getting bothersome.

### CODE REVIEW

**Comment by lrettig** [comment]
Can you not remove lines from .gitignore? Thanks

**Comment by jakelang** [comment]
@lrettig I'm pretty certain that it is old, unused CMake cruft. will keep it anyway

**Comment by lrettig** [comment]
No, the `.idea` is from IntelliJ which I use, I may have added it. Thanks!

**Comment by jakelang** [comment]
@axic can this be merged?

**Comment by axic** [comment]
How about using this: https://www.gitignore.io/api/c,c++,cmake ?

**Comment by jakelang** [comment]
@axic that generated gitignore seems a bit overkill, but I guess I'll just throw that in.

**Comment by axic** [comment]
You are right, some of that looks horrible from gitignore.io.

**Pull request merged**
