### PR TITLE
Run evm2wasm in C++ mode

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chfast** [comment]
You have to build fmt library with PIC. I will fix that.

**Comment by axic** [comment]
Some weird failure:
```
/home/builder/project/test/tools/libtesteth/ImportTest.cpp(751): error: in "GeneralStateTests/stEWASMTests": createFromTransaction on Byzantium: Expected another postState hash! expected: 0xd9f8c57da1d097b75823039a35f2626cbef5bb380363d1cb272497a98d800614 actual: 0x19fc38351a22fc05c8add29df0767dc26ab2635d0b4ed11caf7d7cb6fed2ea4d in Byzantium data: 0 gas: 0 val: 0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::eth::InternalVMError>'
  what():  /home/builder/project/libevm/EVMC.cpp(79): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256 &, dev::eth::ExtVMFace &, const dev::eth::OnOpFunc &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = -1

unknown location(0): fatal error: in "GeneralStateTests/stEWASMTests": signal: SIGABRT (application abort requested)
/home/builder/project/test/tools/libtesteth/TestHelper.cpp(595): last checkpoint
```

**Comment by chfast** [comment]
Hera has returned `EVMC_INTERNAL_ERROR`.

**Comment by axic** [comment]
But it isn't on any other branch and this is the non-evm2wasm ci task. Probably need to rebase this PR>

**Comment by axic** [comment]
Something failed:
```
testeth 1.4.0rc0
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >'
  what():  the argument for option '--vm' is invalid
Received 'aborted' signal
```

**Comment by chfast** [comment]
CMake added `d` suffix to the library name so it is now `libherad.so`. I will fix this.

**Comment by axic** [comment]
> CMake added d suffix to the library name so it is now libherad.so. I will fix this.

With that change now the `shared-release` one is failing :)

**Comment by chfast** [comment]
> With that change now the shared-release one is failing :)

Learning how bash wildcards work :)

**Pull request merged**
