### PR TITLE
[WIP] Fix CREATE control flow

### LINKED ISSUE #122: CREATE doesn't work
See this branch with the test case in order to reproduce: https://github.com/ewasm/tests/tree/create-test

This is all the output I get:

```
Executing...
useGas 300
create0 14 0 132
```

### PR DESCRIPTION
**Pull request by jakelang**
Potentially fixes #122

### CODE REVIEW

**Comment by axic** [comment]
I think this is wrong.

**Comment by chfast** [comment]
Yes, this assumes that the output from CREATE will be empty in case of SUCCESS (what is true). But you have `.clear()` in single place.

**Comment by axic** [comment]
Clear is applied in both cases currently. What is the actual bug this solves?

**Comment by jakelang** [comment]
I looked at it again, this probably doesnt solve the bug but does clean up the code a bit. assuming the client works correctly this should be exactly the same

**Comment by axic** [comment]
Well there's no guarantee on EVM-C for this atm.

**Comment by jakelang** [comment]
That's why it would be helpful to separate the conditionals for output data and return code, so that it is easier to tell if there is something wrong.

**Pull request closed without merging**
